ckbcomp

diff --git a/ckbcomp/PKGBUILD b/ckbcomp/PKGBUILD
--- a/ckbcomp/PKGBUILD
+++ b/ckbcomp/PKGBUILD
@@ -2,7 +2,7 @@
 # Ex-Maintainer: 	Jeroen Bollen <jbinero at gmail dot comau>
 
 pkgname=ckbcomp
-pkgver=1.198
+pkgver=1.203
 pkgrel=1
 pkgdesc="Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol"
 arch=(any)
@@ -10,10 +10,26 @@ url="http://anonscm.debian.org/cgit/d-i/console-setup.git/"
 license=('GPL2')
 depends=('perl')
 source=("http://ftp.de.debian.org/debian/pool/main/c/console-setup/console-setup_${pkgver}.tar.xz")
-sha512sums=('38e6b10e6e232e49eee5de548dcec29ccc319e8b1028b4c95bc9d87ae8cc24ad635cdae87bf6c3f81fa00435bb7560a2605624ec7dd17bb3ae2ab79e22268672')
+sha512sums=('e73ade4a35c7d5e4986587067ab081da8b99acd1013ef2f9de63205f43a0777a917c0ce18e35f0fc95bfe22162ad56e0c92f1f9d657a27681a26d525441bcf2a')
 
 package() {
-    cd console-setup-${pkgver}
+    if [[ -d "${srcdir}/console-setup" ]]
+    then
+        cd console-setup
+    elif [[ -d "${srcdir}/console-setup-${pkgver}" ]]
+    then 
+        cd console-setup-${pkgver} 
+    else
+	echo "Source directory not found.".
+	exit 1
+    fi
+
+
+    if [[ ${?} != 0 ]]
+    then
+        cd console-setup-${pkgver}
+    fi
+
     install -d ${pkgdir}/usr/bin/
     install -m755 Keyboard/ckbcomp ${pkgdir}/usr/bin/
 }
