update

diff --git a/ckbcomp/PKGBUILD b/ckbcomp/PKGBUILD
--- a/ckbcomp/PKGBUILD
+++ b/ckbcomp/PKGBUILD
@@ -1,16 +1,17 @@
 # Maintainer: Nissar Chababy <funilrys at outlook dot com>
-# Ex-Maintainer: 	Jeroen Bollen <jbinero at gmail dot comau>
+# Ex-Maintainer:    Jeroen Bollen <jbinero at gmail dot comau>
 
 pkgname=ckbcomp
-pkgver=1.208
+pkgver=1.226
 pkgrel=1
 pkgdesc="Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol"
 arch=(any)
 url="http://anonscm.debian.org/cgit/d-i/console-setup.git/"
 license=('GPL2')
 depends=('perl')
-source=("http://ftp.de.debian.org/debian/pool/main/c/console-setup/console-setup_${pkgver}.tar.xz")
-sha512sums=('2fbc68bd6cf10e61eae50cef8fa8e26cc293f22d8303969032e2b693e9e4424cd87bcb7a411868694f7fac66365b3ac2f414dd281bc3dd3ad22d52a25e268313')
+source=("http://ftp.debian.org/debian/pool/main/c/console-setup/console-setup_${pkgver}.tar.xz")
+sha512sums=('1b742ec2f43d50d1ab233864fdace5f1bda6ae40d6a3d16768dd804825c769f198e3a0ddb2b4e7420d13678073cd146e7a784e3e5de74f9d2726ba4a01a88006')
+conflicts=(ckbcomp-bin)
 
 package() {
     if [[ -d "${srcdir}/console-setup" ]]
@@ -19,9 +20,12 @@ package() {
     elif [[ -d "${srcdir}/console-setup-${pkgver}" ]]
     then 
         cd console-setup-${pkgver} 
+    elif [[ -d "${srcdir}/work" ]]
+    then
+        cd work
     else
-	echo "Source directory not found.".
-	exit 1
+    echo "Source directory not found.".
+    exit 1
     fi
 
 
